name: AFV
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - curl=7.71.1
  - krb5=1.17.2
  - ld_impl_linux-64=2.35.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libnghttp2=1.41.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.7.9
  - python_abi=3.7
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.34.0
  - tk=8.6.10
  - unzip=6.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - anyio==2.0.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - babel==2.9.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.3
    - bleach==3.2.1
    - bs4==0.0.1
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distro==1.5.0
    - entrypoints==0.3
    - fiona==1.8.18
    - geopandas==0.8.1
    - idna==2.10
    - importlib-metadata==3.3.0
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.2
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyter-server==1.1.4
    - jupyterlab==3.0.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.0.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - munch==2.5.0
    - nbclassic==0.2.5
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.6
    - numpy==1.19.5
    - packaging==20.8
    - pandas==1.2.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.9
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyproj==3.0.0.post1
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyzmq==20.0.0
    - requests==2.25.1
    - send2trash==1.5.0
    - shapely==1.7.1
    - six==1.15.0
    - sniffio==1.2.0
    - soupsieve==2.1
    - tabula-py==2.2.0
    - terminado==0.9.2
    - testpath==0.4.4
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - zipp==3.4.0
prefix: /home/jyao/miniconda3/envs/AFV
